### ISSUE TITLE
Tebi S3 Not working . Error with PHP code

### ISSUE THREAD

**Issue by madhuryadutta** [tebi-cloud/code_examples#2]
**Tebi S3 is not working . I tried the sdk provided in the documentation and also tried with filesytem. 
It return "HTTP 403 InvalidAccessKeyId" . I tried both master key and bucket specific key with all acces.**

`Uploading test file...
Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://learnlaravel.s3.tebi.io/test.jpg"; AWS HTTP error: Client error: `PUT https://learnlaravel.s3.tebi.io/test.jpg` resulted in a `403 Forbidden` response: <?xml version='1.0' encoding='UTF-8'?> <Error> <Code>InvalidAccessKeyId</Code> <Message>The Access Key Id you provid (truncated...) InvalidAccessKeyId (client): The Access Key Id you provided does not exist in our records. - <?xml version='1.0' encoding='UTF-8'?> <Error> <Code>InvalidAccessKeyId</Code> <Message>The Access Key Id you provided does not exist in our records.</Message> <RequestId>s3/1708005175.934897/PJFI</RequestId> <HostId>node-sgp-1</HostId> </Error> ' GuzzleHttp\Exception\ClientException: Client error: `PUT https://learnlaravel.s3.tebi.io/test.jpg` resulted in a `403 Forbidden` response: <?xml version='1.0' encoding='UTF-8'?> <Error> <Code>InvalidAccessKeyId</Code> <Message>The Access Key Id you provid (truncated...) in E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run() #5 E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick() #6 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #7 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #8 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #9 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #10 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #11 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #12 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #13 E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait() #14 E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command)) #15 E:\xampp\htdocs\tebi\index.php(28): Aws\AwsClient->__call('putObject', Array) #16 {main} Next Aws\S3\Exception\S3Exception: Error executing "PutObject" on "https://learnlaravel.s3.tebi.io/test.jpg"; AWS HTTP error: Client error: `PUT https://learnlaravel.s3.tebi.io/test.jpg` resulted in a `403 Forbidden` response: <?xml version='1.0' encoding='UTF-8'?> <Error> <Code>InvalidAccessKeyId</Code> <Message>The Access Key Id you provid (truncated...) InvalidAccessKeyId (client): The Access Key Id you provided does not exist in our records. - <?xml version='1.0' encoding='UTF-8'?> <Error> <Code>InvalidAccessKeyId</Code> <Message>The Access Key Id you provided does not exist in our records.</Message> <RequestId>s3/1708005175.934897/PJFI</RequestId> <HostId>node-sgp-1</HostId> </Error> in E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php:196 Stack trace: #0 E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array) #1 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(209): Aws\WrappedHttpHandler->Aws\{closure}(Array) #2 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, NULL) #3 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\RejectedPromise.php(49): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array) #4 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}() #5 E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run() #6 E:\xampp\htdocs\tebi\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick() #7 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #8 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #9 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #10 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #11 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #12 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #13 E:\xampp\htdocs\tebi\vendor\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #14 E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait() #15 E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command)) #16 E:\xampp\htdocs\tebi\index.php(28): Aws\AwsClient->__call('putObject', Array) #17 {main} thrown in E:\xampp\htdocs\tebi\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php on line 196`

**Comment by tebi-cloud** [comment]
Hello,
We've updated the PHP code example to make it simpler and easier to understand. A working example is shared privately in the ticket that you opened with us, I hope this will help you to find the problem in the Laravel project you are working on.
Thanks!

**Comment by madhuryadutta** [comment]
Thank you for your help, @tebi-cloud .I got the updated codes.
I have tested the PHP code (from a Linux server), its working fine .  Tebi S3 is also working perfectly with Laravel File system .
**Problem Solved :+1:  **

Note:---
_Previously, I tried the project from my windows machine ,which resulted in this error .The error may be it related to my system ,But i will requested you to also test the codes from a windows system._
